export const table=[
    {id:1,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:2,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:3,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:4,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:5,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:6,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:7,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:8,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:9,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:10,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:11,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:12,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:13,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:14,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:15,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:16,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:17,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:18,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:19,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
    {id:20,name:'Jamshidbek',age:'18',address:"Nmangan,Uzbekistan",status: 'Student ', job:'Frontent Developer'},
]